### ISSUE TITLE
if scrollToElement: false, finish button not working

### ISSUE THREAD

**Issue by serdarkok** [heminei/jquery-hemi-intro#1]
Hi, 
Thanks awesome script. 

If i choose "scrollToElement: false", finish button visible but not working. Finish button is not close to tooltip. How can i get solution this issue.

Thanks

**Comment by heminei** [comment]
Hi,
Please, send me demo url.

**Comment by serdarkok** [comment]
I am working localhost. I will turn back you when i upload files at remote.
