### ISSUE TITLE
Detect events

### ISSUE THREAD

**Issue by rodrigonormandia** [heminei/jquery-hemi-intro#2]
Hi dude, this plugin is awesome but I need some help. How is possible to know if the tour is complete ou runing?

**Comment by heminei** [comment]
Hello,
Thank you for the intereset in my plugin. To answer your question, there are callbacks for each state of the plugin.

For example, if you want to keep the current step in a variable, you can write your own functions in the onAfterChangeStep event which you can simply increment the variable. This function will be called each time a new step is progressed.

As for the completion, there is a callback function onComplete, where you can add your custom function that will be called once the intro is completed.

I hope this answers your questions.

Regards,
Martin
